%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/Aurina/GoogleDrive/Genetics_connectome/HumanExpression/data/genes/rawData/normalized_microarray_donor01/SampleAnnot.xlsx
%    Worksheet: SampleAnnot.csv
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/01/09 15:02:00

%% Import the data
function structureID = importStructureInfo(filename)
[~, ~, raw] = xlsread(filename);
raw = raw(:,1);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
structureID = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;
end